In [8]:
import numpy as np

# Dữ liệu đề bài
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([
    [1, 2, -1],
    [0, 3, 4],
    [2, -1, 0]
])

# --- a) Tính tổng A + B và tích số 3A - 2B ---
sum_AB = A + B
scalar_expr = 3 * A - 2 * B

print("a) Tổng A + B:", sum_AB)
print("   Biểu thức 3A - 2B:", scalar_expr)

# --- b) Tích vô hướng A · B và góc giữa hai vector ---
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)

# Góc giữa 2 vector (theo độ)
cos_theta = dot_product / (norm_A * norm_B)
angle_rad = np.arccos(np.clip(cos_theta, -1.0, 1.0))
angle_deg = np.degrees(angle_rad)

print("\nb) Tích vô hướng A · B:", dot_product)
print("   Góc giữa A và B (độ):", round(angle_deg, 3), "°")

# --- c) Tính tích ma trận CᵀC ---
C_T = C.T
CTC = np.dot(C_T, C)

print("\nc) Ma trận tích CᵀC là:")
print(CTC)




a) Tổng A + B: [3 3 1 5]
   Biểu thức 3A - 2B: [  4 -11  13 -10]

b) Tích vô hướng A · B: -8
   Góc giữa A và B (độ): 108.376 °

c) Ma trận tích CᵀC là:
[[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]
