In [3]:
import numpy as np

# --- Dữ liệu đề bài ---
M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])

N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

# --- a) Tính tích M × N ---
MN = np.dot(M, N)
print("a) Ma trận tích M × N là:")
print(MN)

# --- b) Tính định thức của ma trận M ---
try:
    det_M = np.linalg.det(M)
    print("\nb) Định thức của ma trận M là:", det_M)
    if np.isclose(det_M, 0):
        print("→ Ma trận M không khả nghịch vì định thức = 0.")
except np.linalg.LinAlgError:
    print("\nb) Không thể tính định thức của M (không là ma trận vuông).")

# --- c) Tính hạng của ma trận N ---
rank_N = np.linalg.matrix_rank(N)
print("\nc) Hạng của ma trận N là:", rank_N)


a) Ma trận tích M × N là:
[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

b) Định thức của ma trận M là: 6.66133814775094e-16
→ Ma trận M không khả nghịch vì định thức = 0.

c) Hạng của ma trận N là: 2
