In [3]:
import numpy as np

# --- Dữ liệu đề bài ---
P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])

b = np.array([4, 7, 0, 9])  # vector hằng số từ hệ phương trình

# --- a) Tìm ma trận nghịch đảo ---
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P là:")
    print(P_inv)
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch vì định thức bằng 0.")

# --- b) Giải hệ phương trình bằng nghịch đảo ---
if 'P_inv' in locals():
    x = np.dot(P_inv, b)
    print("\nb) Nghiệm của hệ phương trình là (x, y, z, w):")
    print(x)

# --- c) Kiểm tra nghiệm ---
if 'x' in locals():
    b_check = np.dot(P, x)
    print("\nc) Kiểm tra lại nghiệm (P * x):")
    print(b_check)
    print("So với vector hằng số ban đầu:")
    print(b)




a) Ma trận nghịch đảo của P là:
[[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]

b) Nghiệm của hệ phương trình là (x, y, z, w):
[-0.58139535  3.24418605 -0.81395349  1.91860465]

c) Kiểm tra lại nghiệm (P * x):
[ 4.0000000e+00  7.0000000e+00 -4.4408921e-16  9.0000000e+00]
So với vector hằng số ban đầu:
[4 7 0 9]
