In [2]:
import numpy as np

A = np.array([[1, 2],
              [2, 1]])

# a) Tính trị riêng và vector riêng
eigenvalues, eigenvectors = np.linalg.eig(A)
print("a) Giá trị riêng:")
print(eigenvalues)
print("\nVector riêng:")
print(eigenvectors)

# b) Kiểm tra A * v = λ * v
for i in range(len(eigenvalues)):
    lam = eigenvalues[i]
    v = eigenvectors[:, i]
    left = A @ v
    right = lam * v
    print(f"\n\nb) Kiểm tra với trị riêng λ = {lam}")
    print("A * v =", left)
    print("λ * v =", right)

# c) Đường chéo hóa nếu có thể
try:
    P = eigenvectors
    D = np.diag(eigenvalues)
    P_inv = np.linalg.inv(P)
    A_reconstructed = P @ D @ P_inv

    print("\n\nc) Ma trận đường chéo D:")
    print(D)
    print("\nMa trận P⁻¹:")
    print(P_inv)
    print("\nPhục hồi A từ P * D * P⁻¹:")
    print(A_reconstructed)
except np.linalg.LinAlgError:
    print("\nKhông thể đường chéo hóa ma trận.")



a) Giá trị riêng:
[ 3. -1.]

Vector riêng:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


b) Kiểm tra với trị riêng λ = 3.0000000000000004
A * v = [2.12132034 2.12132034]
λ * v = [2.12132034 2.12132034]


b) Kiểm tra với trị riêng λ = -0.9999999999999996
A * v = [ 0.70710678 -0.70710678]
λ * v = [ 0.70710678 -0.70710678]


c) Ma trận đường chéo D:
[[ 3.  0.]
 [ 0. -1.]]

Ma trận P⁻¹:
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Phục hồi A từ P * D * P⁻¹:
[[1. 2.]
 [2. 1.]]
