In [4]:
#1.1. Thông tin tóm gọn 
import numpy as np

# Khởi tạo mảng D
D = np.array([[1, 2], [3, 4]])

# Chưa khởi tạo E, cố gắng copy D vào E
try:
    np.copyto(E, D)
except NameError as e:
    print("Lỗi khi thực hiện np.copyto(E, D):", e)

# Khởi tạo mảng E
E = np.array([[1, 2], [3, 5]])

# Copy nội dung của D vào E
np.copyto(E, D)

# In ra mảng E sau khi copy
print("Mảng E sau khi copy:")
print(E)

#1.2. Nên và không nên sử dụng kiểu dữ liệu numpy.matrix
import numpy as np

# Tạo mảng x
x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'

# Tạo matrix C từ x, y, 1, 2
import numpy as np

x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'

C = np.array([[x, y], [1, 2]], dtype=object)
print(C)

# Ghi nhận lỗi khi tạo np.matrix 3 chiều
try:
    A = np.matrix([[[1,2],[3,4]], [[5,6],[7,8]]])
except Exception as e:
    print("Lỗi khi tạo np.matrix 3 chiều:", e)
print()

# Tạo array 3 chiều thành công
A = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print("Kết quả của A (numpy array 3 chiều):")
print(A)
#1.3. Đối tượng matrix từ các hàm trong gói numpy.matlib 
from numpy import matlib

# Tạo ma trận đơn vị 5x5
G = matlib.identity(5)  # cú pháp: matlib.identity(n)
print("Ma trận đơn vị 5x5 G:")
print(G)
print()

# Tạo ma trận 3x2 với các số ngẫu nhiên chuẩn (gaussian)
H = matlib.randn(3, 2)  # cú pháp: matlib.randn(*args)
print("Ma trận ngẫu nhiên 3x2 H:")
print(H)
print()

# Tạo ma trận 4x4 toàn số 0
K = matlib.zeros([4, 4])  # cú pháp: matlib.zeros(shape)
print("Ma trận 4x4 toàn số 0 K:")
print(K)




Mảng E sau khi copy:
[[1 2]
 [3 4]]
[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]
Lỗi khi tạo np.matrix 3 chiều: matrix must be 2-dimensional

Kết quả của A (numpy array 3 chiều):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Ma trận đơn vị 5x5 G:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Ma trận ngẫu nhiên 3x2 H:
[[-1.03329724 -3.2893409 ]
 [ 0.88218729 -1.20346572]
 [ 0.43952188 -1.315919  ]]

Ma trận 4x4 toàn số 0 K:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
#2. Ứng dụng 2 –Liên phân số và số 
import numpy as np

c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]  # dãy phân số biểu diễn Pi

M = np.asmatrix([[1, 2], [3, 4]])  # khởi tạo ma trận 2x2 (không dùng ngay)

for i in range(len(c)):
    ci = np.asmatrix([[1, 1], [1, 0]])
    ci[0, 0] = c[i]
    if i == 0:
        M = ci
    else:
        M = M.dot(ci)

print("Ma trận M sau khi nhân liên tục:")
print(M)

pi_approx = M[0, 0] / M[1, 0]
print("Giá trị xấp xỉ số Pi tính được:", pi_approx)


Ma trận M sau khi nhân liên tục:
[[165707065  80143857]
 [ 52746197  25510582]]
Giá trị xấp xỉ số Pi tính được: 3.1415926535897936


In [7]:
#3. Về phân tích hồi quy tuyến tính 
import numpy as np

# Nhập dữ liệu X (ma trận 5x2), mỗi hàng là một điểm dữ liệu, cột đầu là 1
X = np.array([
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4],
    [1, 5]
])

# Vector kết quả Y
Y = np.array([1, 2, 4, 4, 6])

# Tính chuyển vị của X
XT = X.T

# Tính A1 = (X^T X)^(-1)
A1 = np.linalg.inv(XT.dot(X))

# Tính A2 = X^T Y
A2 = XT.dot(Y)

# Tính vector A = A1.dot(A2)
A = A1.dot(A2)

print("Vector nghiệm A (chứa intercept và hệ số góc):")
print(A)

# Phương trình hồi quy gần đúng là:
# Y = A[0] + A[1]*X

# Tính giá trị dự đoán Y_pred
Y_pred = X.dot(A)

# Tính sai số là tổng bình phương sai số
error = np.sum((Y - Y_pred) ** 2)
print("Tổng bình phương sai số:", error)


Vector nghiệm A (chứa intercept và hệ số góc):
[-0.2  1.2]
Tổng bình phương sai số: 0.8000000000000003


# BÀI TẬP CHƯƠNG 5

In [8]:
import numpy as np

def bpcuctieu(a):
    b = []
    o1 = []
    for i in range(len(a)):
        o1.append(1.0)        # cột hệ số chệch (intercept)
        b.append(i * 1.0)     # cột biến độc lập (thời gian)

    # Xây dựng ma trận dữ liệu (2 x n) gồm cột 1 và cột biến thời gian
    x = np.array([o1, b])    # kích thước (2, n)

    # Tính u = x . x^T
    u = np.dot(x, x.T)       # kích thước (2, 2)

    # Vector kết quả y (lượng thuốc)
    y = np.array(a)          # kích thước (n,)

    from numpy import linalg

    # Tính nghịch đảo của u
    u_1 = np.linalg.inv(u)

    # Tính v = u_1 . x
    v = np.dot(u_1, x)       # kích thước (2, n)

    # Tính hệ số A = v . y
    A = np.dot(v, y)

    return A

# Dữ liệu lượng thuốc theo thời gian
dulieu = [10.0, 8, 7, 5, 2]

# Gọi hàm
A = bpcuctieu(dulieu)

print(f"Hệ số phương trình tuyến tính y = a0 + a1*x là:")
print(f"a0 (intercept) = {A[0]}")
print(f"a1 (hệ số góc) = {A[1]}")

print(f"Phương trình gần đúng: y = {A[0]:.2f} + ({A[1]:.2f}) * x")


Hệ số phương trình tuyến tính y = a0 + a1*x là:
a0 (intercept) = 10.200000000000001
a1 (hệ số góc) = -1.9
Phương trình gần đúng: y = 10.20 + (-1.90) * x
