# CHƯƠNG 3: MA TRẬN VÀ HỆ PHƯƠNG TRÌNH TUYẾN TÍNH

In [2]:
# 1.1. Một số phép xử lý ma trận của NumPy và Scipy 
from scipy import linalg
import numpy as np

# Khởi tạo mảng
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[(0.5, 1.5, 10), (3, 2, 1)], [(6, 5, 4), (7, 8, 9)]])

# Khai báo và khởi tạo ma trận
A = np.matrix(np.random.random((2, 2)))
B = np.asmatrix(b)
C = np.mat(np.random.random((10, 5)))
D = np.mat([[4, 3], [2, 6]])
F = np.eye(3, k=1)

print("F (k=1) - Kết quả là:\n", F)

F = np.eye(3, k=0)
print("F (k=0) - Kết quả là:\n", F)

F = np.eye(3, k=-1)
print("F (k=-1) - Kết quả là:\n", F)

# Hạng ma trận
print("Rank of C - Kết quả là:", np.linalg.matrix_rank(C))

# Ma trận nghịch đảo
print("A.I - Kết quả là:\n", A.I)
print("inv(A) - Kết quả là:\n", linalg.inv(A))

# Định thức
print("det(A) - Kết quả là:", linalg.det(A))

# Chuyển vị và chuyển vị liên hợp
print("A.T - Kết quả là:\n", A.T)
print("A.H (Hermitian) - Kết quả là:\n", A.H)

# Giải hệ phương trình tuyến tính
try:
    print("solve(A, a[:2]) - Kết quả là:", linalg.solve(A, a[:2]))
except Exception as e:
    print("solve(A, a[:2]) - Lỗi:", e)

# Ma trận chuyển vị từ vector a
E = np.mat(a).T
print("E = np.mat(a).T - Kết quả là:\n", E)

# Giải hệ gần đúng: F*x = E
try:
    print("lstsq(F, E) - Kết quả là:", linalg.lstsq(F, E))
except Exception as e:
    print("lstsq - Lỗi:", e)

# Các phép toán ma trận
print("A + D - Kết quả là:\n", np.add(A, D))
print("A - D - Kết quả là:\n", np.subtract(A, D))
print("A / D - Kết quả là:\n", np.divide(A, D))

print("A @ D - Kết quả là:\n", A @ D)
print("D * A (element-wise) - Kết quả là:\n", np.multiply(D, A))
print("dot(A, D) - Kết quả là:\n", np.dot(A, D))
print("vdot(A, D) - Kết quả là:", np.vdot(A, D))

# Lũy thừa và logarit ma trận
print("expm(A) - Kết quả là:\n", linalg.expm(A))
print("logm(A) - Kết quả là:\n", linalg.logm(A))



F (k=1) - Kết quả là:
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
F (k=0) - Kết quả là:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
F (k=-1) - Kết quả là:
 [[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
Rank of C - Kết quả là: 5
A.I - Kết quả là:
 [[ 1.63036304 -0.12168693]
 [-0.52171798  2.14390972]]
inv(A) - Kết quả là:
 [[ 1.63036304 -0.12168693]
 [-0.52171798  2.14390972]]
det(A) - Kết quả là: 0.29138676088390836
A.T - Kết quả là:
 [[0.62470691 0.15202171]
 [0.03545796 0.4750662 ]]
A.H (Hermitian) - Kết quả là:
 [[0.62470691 0.15202171]
 [0.03545796 0.4750662 ]]
solve(A, a[:2]) - Kết quả là: [1.38698919 3.76610146]
E = np.mat(a).T - Kết quả là:
 [[1]
 [2]
 [3]]
lstsq(F, E) - Kết quả là: (array([[2.],
       [3.],
       [0.]]), array([], dtype=float64), 2, array([1., 1., 0.]))
A + D - Kết quả là:
 [[4.62470691 3.03545796]
 [2.15202171 6.4750662 ]]
A - D - Kết quả là:
 [[-3.37529309 -2.96454204]
 [-1.84797829 -5.5249338 ]]
A / D - Kết quả là:
 [[0.15617673 0.01181932]
 [0.07601086 0.0791777 ]]
A @ D - Kế

In [9]:
# 2.3 Ma trận hội tụ
import numpy as np

print(">>> Ma trận A:")
A = np.array([[0, 1], [1, 0]])
print("Kết quả là:\n", A)

temp = A.dot(A)
print("Lũy thừa lần 1:\n", temp)

k = 6
for i in range(k-1):
    temp = temp.dot(A)
    print(f"Lũy thừa lần {i+2}:\n{temp}")
    

print(">>> Ma trận B:")
B = np.array([[0, -1], [-1, 0]])
print("Kết quả là:\n", B)

temp = B.dot(B)
print("Lũy thừa lần 1:\n", temp)

k = 5
for i in range(k-1):
    temp = temp.dot(B)
    print(f"Lũy thừa lần {i+2}:\n{temp}")
    
print(">>> Ma trận C:")
C = np.array([[1, 0, 0], [0, 0.5, 1], [0, 0, 0.5]])
print("Kết quả là:\n", C)

temp = C.dot(C)
print("Lũy thừa lần 1:\n", temp)

k = 1000
for i in range(k - 1):
    temp = temp.dot(C)

print("Sau 1000 lũy thừa lần đầu - Kết quả là:\n", temp)

for i in range(k - 1):
    temp = temp.dot(C)

print("Sau 1000 lũy thừa tiếp theo - Kết quả là:\n", temp)


>>> Ma trận A:
Kết quả là:
 [[0 1]
 [1 0]]
Lũy thừa lần 1:
 [[1 0]
 [0 1]]
Lũy thừa lần 2:
[[0 1]
 [1 0]]
Lũy thừa lần 3:
[[1 0]
 [0 1]]
Lũy thừa lần 4:
[[0 1]
 [1 0]]
Lũy thừa lần 5:
[[1 0]
 [0 1]]
Lũy thừa lần 6:
[[0 1]
 [1 0]]
>>> Ma trận B:
Kết quả là:
 [[ 0 -1]
 [-1  0]]
Lũy thừa lần 1:
 [[1 0]
 [0 1]]
Lũy thừa lần 2:
[[ 0 -1]
 [-1  0]]
Lũy thừa lần 3:
[[1 0]
 [0 1]]
Lũy thừa lần 4:
[[ 0 -1]
 [-1  0]]
Lũy thừa lần 5:
[[1 0]
 [0 1]]
>>> Ma trận C:
Kết quả là:
 [[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
Lũy thừa lần 1:
 [[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
Sau 1000 lũy thừa lần đầu - Kết quả là:
 [[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
Sau 1000 lũy thừa tiếp theo - Kết quả là:
 [[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# 2.4. Ma trận Markov 
import numpy as np

M = np.array([[0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M)  # M^2
print("M^2 - Kết quả là:\n", MM)

MM = MM.dot(M)  # M^3
print("M^3 - Kết quả là:\n", MM)

for i in range(100):
    MM = MM.dot(M)

print("M^103 - Kết quả là:\n", MM)

M = np.array([[0.5, 0.5], [0.5, 0.5]])
MM = M.dot(M)
print("M^2 - Kết quả là:\n", MM)

MM = MM.dot(M)
print("M^3 - Kết quả là:\n", MM)

for i in range(100):
    MM = MM.dot(M)

print("M^103 - Kết quả là:\n", MM)


M^2 - Kết quả là:
 [[0.7  0.45]
 [0.3  0.55]]
M^3 - Kết quả là:
 [[0.65  0.525]
 [0.35  0.475]]
M^103 - Kết quả là:
 [[0.6 0.6]
 [0.4 0.4]]
M^2 - Kết quả là:
 [[0.5 0.5]
 [0.5 0.5]]
M^3 - Kết quả là:
 [[0.5 0.5]
 [0.5 0.5]]
M^103 - Kết quả là:
 [[0.5 0.5]
 [0.5 0.5]]


In [11]:
# 3.2. Phân rã ma trận LU
import numpy as np
from scipy import linalg

M = np.array([[0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M)

print("Ma trận P:\n", P)
print("Ma trận L:\n", L)
print("Ma trận U:\n", U)

print("L.dot(U) (so sánh với P.T @ M):\n", L.dot(U))
print("P.T @ M:\n", P.T.dot(M))  # để so sánh đối chiếu


Ma trận P:
 [[1. 0.]
 [0. 1.]]
Ma trận L:
 [[1.   0.  ]
 [0.25 1.  ]]
Ma trận U:
 [[0.8   0.3  ]
 [0.    0.625]]
L.dot(U) (so sánh với P.T @ M):
 [[0.8 0.3]
 [0.2 0.7]]
P.T @ M:
 [[0.8 0.3]
 [0.2 0.7]]


In [13]:
# 4. Bài toán ứng dụng 1 – Căn bản về mật mã học, mã hóa thông tin, mật khẩu 
import numpy as np

# Khởi tạo ma trận mã hóa
M = np.array([[3, 1, -2],
              [2, -1, 1],
              [1, -1, -4]])

# Danh sách các chuỗi số đã mã hóa
data = [
    [13, 11, 17],
    [1, 0, 11],
    [17, 34, 5],
    [0, 6, 26],
    [33, 0, 14],
    [12, 9, 34],
    [25, 35, 35]
]

print("KẾT QUẢ MÃ HÓA:")
for i, vec in enumerate(data, 1):
    result = np.dot(vec, M)
    print(f"Mã hóa {i}: {vec} x M = {result}")

# Giải mã (phục hồi lại vector gốc)
Minv = np.linalg.inv(M)
print("\nPHỤC HỒI DỮ LIỆU:")
for i, vec in enumerate(data, 1):
    encoded = np.dot(vec, M)
    recovered = np.round(np.dot(encoded, Minv)).astype(int)  # làm tròn và chuyển về int
    print(f"Giải mã {i}: {encoded} x M⁻¹ = {recovered}")


KẾT QUẢ MÃ HÓA:
Mã hóa 1: [13, 11, 17] x M = [ 78 -15 -83]
Mã hóa 2: [1, 0, 11] x M = [ 14 -10 -46]
Mã hóa 3: [17, 34, 5] x M = [124 -22 -20]
Mã hóa 4: [0, 6, 26] x M = [ 38 -32 -98]
Mã hóa 5: [33, 0, 14] x M = [ 113   19 -122]
Mã hóa 6: [12, 9, 34] x M = [  88  -31 -151]
Mã hóa 7: [25, 35, 35] x M = [ 180  -45 -155]

PHỤC HỒI DỮ LIỆU:
Giải mã 1: [ 78 -15 -83] x M⁻¹ = [13 11 17]
Giải mã 2: [ 14 -10 -46] x M⁻¹ = [ 1  0 11]
Giải mã 3: [124 -22 -20] x M⁻¹ = [17 34  5]
Giải mã 4: [ 38 -32 -98] x M⁻¹ = [ 0  6 26]
Giải mã 5: [ 113   19 -122] x M⁻¹ = [33  0 14]
Giải mã 6: [  88  -31 -151] x M⁻¹ = [12  9 34]
Giải mã 7: [ 180  -45 -155] x M⁻¹ = [25 35 35]


In [14]:
# 5. Bài toán ứng dụng 2 – Bài toán loan tin 
import numpy as np

# Khởi tạo ma trận A
A = np.array([[0, 1, 0, 1],
              [0, 0, 1, 0],
              [1, 0, 0, 1],
              [1, 1, 0, 0]])

# Tính A^2
temp = A @ A
print("A^2 =\n", temp)

# Tính A^3
temp = temp @ A
print("A^3 =\n", temp)

# Tính tổng A + A^2 + A^3
sumA = A + A @ A + A @ A @ A
print("Tổng A + A^2 + A^3 =\n", sumA)


A^2 =
 [[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
A^3 =
 [[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
Tổng A + A^2 + A^3 =
 [[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


# BÀI TẬP CHƯƠNG 3 

In [16]:
# Câu 1: Hãy viết chương trình bằng Python hoặc sử dụng thư viện numpy/sympy để:import numpy as np

# a. Chọn ma trận khả nghịch 3x3
A = np.array([[2, 1, 3],
              [1, 1, 1],
              [1, -1, 2]])
inv_A = np.linalg.inv(A)
print("Ma trận A:\n", A)
print("Ma trận nghịch đảo A⁻¹:\n", inv_A)

# b. Nhập họ tên hoặc MSSV
text = "Ngo Vinh Thành"  

# c. Mã hóa chuỗi thành mã ASCII và chia thành các nhóm 3
ascii_vals = [ord(c) for c in text]
while len(ascii_vals) % 3 != 0:
    ascii_vals.append(0)  # thêm 0 để đủ chia 3

vectors = np.array(ascii_vals).reshape(-1, 3).T
print("Mã ASCII dạng vector:\n", vectors)

# Mã hóa: nhân ma trận
encoded = A @ vectors
print("Mã hóa:\n", encoded)

# d. Giải mã: nhân với ma trận nghịch đảo và làm tròn
decoded = np.round(inv_A @ encoded).astype(int)
decoded_text = ''.join(chr(c) for c in decoded.T.flatten() if c > 0)
print("Giải mã:\n", decoded_text)


Ma trận A:
 [[ 2  1  3]
 [ 1  1  1]
 [ 1 -1  2]]
Ma trận nghịch đảo A⁻¹:
 [[-3.  5.  2.]
 [ 1. -1. -1.]
 [ 2. -3. -1.]]
Mã ASCII dạng vector:
 [[ 78  32 110  84 110]
 [103  86 104 104 104]
 [111 105  32 224   0]]
Mã hóa:
 [[592 465 420 944 324]
 [292 223 246 412 214]
 [197 156  70 428   6]]
Giải mã:
 Ngo Vinh Thành


In [17]:
# Câu 2: Tính toán phân số từ liên phân số (continued fractions)
import numpy as np

def continued_fraction_to_fraction(cf):
    M = np.array([[cf[0], 1], [1, 0]])  # Khởi tạo ma trận đầu tiên
    for a in cf[1:]:
        M = M @ np.array([[a, 1], [1, 0]])  # Nhân chuỗi ma trận
    return M[0, 0], M[1, 0]  # Trả về tử và mẫu số

# Ví dụ: Liên phân số của 8/3 là [2, 1, 2]
cf_list = [2, 1, 2]
p, q = continued_fraction_to_fraction(cf_list)
print(f"Kết quả: {p}/{q}")  # Kết quả: 8/3


Kết quả: 8/3
