In [1]:
# Bài 1.2
import numpy as np

# Khai báo hai vector a và b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
tich_vo_huong = np.inner(a, b)
print("Tích vô hướng của a và b (np.inner):", tich_vo_huong)

tich_dot = np.dot(a, b)
print("Tích vô hướng của a và b (np.dot):", tich_dot)

p = np.array([[1, 2], [3, 4]])
q = np.array([[5, 6], [7, 8]])

tich_inner_2d = np.inner(p, q)
print("np.inner với ma trận 2x2:\n", tich_inner_2d)

tich_dot_2d = np.dot(p, q)
print("np.dot với ma trận 2x2:\n", tich_dot_2d)

x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 1, 1], [1, 1, 1]])

z = np.dot(x, y)
print("np.dot với (2x2) * (2x3):\n", z)


Tích vô hướng của a và b (np.inner): 32
Tích vô hướng của a và b (np.dot): 32
np.inner với ma trận 2x2:
 [[17 23]
 [39 53]]
np.dot với ma trận 2x2:
 [[19 22]
 [43 50]]
np.dot với (2x2) * (2x3):
 [[3 3 3]
 [7 7 7]]


In [ ]:
import numpy as np
import math
from scipy import linalg

def chuan(v, k):
    tong = 0
    for i in range(len(v)):
        tong += abs(v[i])**k
    ketqua = tong**(1.0/k)
    return ketqua
a = np.array([1, 2, -3])

print("==> Chuẩn 2 (euclidean):", np.linalg.norm(a))
print("==> Chuẩn 1 (tổng trị tuyệt đối):", np.linalg.norm(a, 1))

# Thử các chuẩn khác
print("==> Chuẩn 3:", chuan(a, 3))
print("==> np.linalg.norm với chuẩn 3:", np.linalg.norm(a, 3))

# Chuẩn lớn hơn (ví dụ chuẩn 1000)
print("==> Chuẩn 1000 (gần max(abs(a))):", chuan(a, 1000))
print("==> np.linalg.norm(a, 1000):", np.linalg.norm(a, 1000))

# ------------------------------------
# Tính khoảng cách giữa hai vector
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
khoang_cach = np.linalg.norm(u - v)
print("==> Khoảng cách giữa u và v:", khoang_cach)
def goc_giua_2_vector(u, v):
    tu = np.inner(u, v)
    mau = np.linalg.norm(u) * np.linalg.norm(v)
    cos_theta = tu / mau
    theta = np.arccos(np.clip(cos_theta, -1.0, 1.0))
    return np.degrees(theta)

print("==> Góc giữa u và v (độ):", goc_giua_2_vector(u, v))

def phep_chieu(u, v):
    tu = np.inner(u, v)
    mau = np.inner(v, v)
    p = (tu / mau) * v
    return p

chieu_uv = phep_chieu(u, v)
print("==> Phép chiếu trực giao của u lên v:", chieu_uv)

def kiem_tra_truc_giao(u, v):
    tong_binh = np.linalg.norm(u + v)**2
    tung_binh = np.linalg.norm(u)**2 + np.linalg.norm(v)**2
    return math.isclose(tong_binh, tung_binh)

print("==> Kiểm tra u ⊥ v (theo định lý Pythagoras):", kiem_tra_truc_giao(u, v))


In [2]:
# Bài 2
import numpy as np
m = 10

v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])

mi = np.array([2, 2, 2, 4])
M = np.array([v1, v2, v3, v4])

MT = M.transpose()
print("Ma trận chuyển vị MT:\n", MT)

v = (1.0 / m) * MT.dot(mi)
print("Vector trọng tâm là:", v)


Ma trận chuyển vị MT:
 [[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
Vector trọng tâm là: [-2.6  2.4  2.4]


In [3]:
# Bài 3.1
import numpy as np
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])
v0 = np.array([0.95, 0.05])

A_100 = np.linalg.matrix_power(A, 100)
v100 = A_100.dot(v0)

print("Ma trận A^100 là:\n", A_100)
print("Vector v100 sau 100 tuần là:\n", v100)

x100, y100 = v100
print("x100 =", x100)
print("y100 =", y100)


Ma trận A^100 là:
 [[0.98550725 0.9855069 ]
 [0.01449275 0.0144931 ]]
Vector v100 sau 100 tuần là:
 [0.98550723 0.01449277]
x100 = 0.9855072337572737
y100 = 0.01449276624272995


In [5]:
import sympy as sym
x, y = sym.symbols('x y')

A = sym.Matrix([[1, -68], [1, 1]])
v = sym.Matrix([0, 1])
xy = sym.Matrix([x, y])
nghiem = sym.solve([A * xy - v], (x, y))

print("Nghiệm bằng sympy là:")
print(sym.pretty(nghiem))


Nghiệm bằng sympy là:
⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [4]:
# Bài 3.2
import numpy as np
import sympy as sym

A = np.array([[1, 6],
              [5, 2]])

u = np.array([6, -5])
lam = -4
Au = A.dot(u)
lam_u = lam * u

print("A * u =", Au)
print("-4 * u =", lam_u)
print("Au = -4u?", np.allclose(Au, lam_u))
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Các trị riêng (eigenvalues):", eigenvalues)
print("Các vector riêng (eigenvectors):\n", eigenvectors)

x = sym.symbols('x')
A_sym = sym.Matrix([[1, 6],
                    [5, 2]])

I = sym.eye(2)
det = (A_sym - x * I).det()

print("Đa thức đặc trưng (characteristic polynomial):")
sym.pprint(det)
eigenvals = sym.solve(det, x)
print("Các trị riêng tìm được:", eigenvals)


A * u = [-24  20]
-4 * u = [-24  20]
Au = -4u? True
Các trị riêng (eigenvalues): [-4.  7.]
Các vector riêng (eigenvectors):
 [[-0.76822128 -0.70710678]
 [ 0.6401844  -0.70710678]]
Đa thức đặc trưng (characteristic polynomial):
 2           
x  - 3⋅x - 28
Các trị riêng tìm được: [-4, 7]


In [6]:
import sympy

x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2, 3],
                  [3, -6]])

phuongtrinh = sympy.Eq(sympy.det(Lambda * I - A), 0)
nghiem = sympy.solve(phuongtrinh)
print("Trị riêng (dạng số gần đúng):")
print([sympy.N(phantu, 4) for phantu in nghiem])

print("\nTrị riêng (dạng biểu thức):")
print(sympy.pretty(nghiem))


Trị riêng (dạng số gần đúng):
[-7.000, 3.000]

Trị riêng (dạng biểu thức):
[-7, 3]


In [7]:
# Bài 3.3
import numpy as np
from numpy.linalg import inv

A = np.array([[2, 3],
              [3, -6]])
D = np.array([[-7, 0],
              [ 0, 3]])
P = np.array([[-1.0/3, 3],
              [1,      1]])

P_inv = inv(P)
print("Ma trận P nghịch đảo (P^(-1)):")
print(P_inv)
print("\nA.dot(P):")
print(A.dot(P))

print("\nP.dot(D):")
print(P.dot(D))
D_pow = np.linalg.matrix_power(D, 1000)
A_pow = P @ D_pow @ P_inv

print("\nMa trận A^1000 tính bằng chéo hóa:")
print(np.round(A_pow, 4))
print("\nD ** 2 (bình phương ma trận đường chéo):")
print(np.linalg.matrix_power(D, 2))


Ma trận P nghịch đảo (P^(-1)):
[[-0.3  0.9]
 [ 0.3  0.1]]

A.dot(P):
[[ 2.33333333  9.        ]
 [-7.          3.        ]]

P.dot(D):
[[ 2.33333333  9.        ]
 [-7.          3.        ]]

Ma trận A^1000 tính bằng chéo hóa:
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]

D ** 2 (bình phương ma trận đường chéo):
[[49  0]
 [ 0  9]]


Bài Tập về Nha


Bài 1
Câu 1: [Trắc nghiệm] Trong Python 3, các câu lệnh sau đây, câu lệnh nào tính chuẩn 2 của
vector a. Với a được xác định là:
>>> import numpy as np
>>> a = np.array([1,2,3])
a. >>> mag = np.sqrt(a.dot(a))
b. >>> mag = np.sqrt(a @ a )
c. >>> mag = np.sqrt(np.inner(a,a))
d. >>> mag = lambda x : math.sqrt(sum(i** 2 for i in x))
>>> mag(a)

a. >>> mag = np.sqrt(a.dot(a))

In [8]:
#Bài 2
import numpy as np

def khoang_cach(u, v):
    return np.linalg.norm(u - v)
def goc_giua(u, v):
    dot_product = np.dot(u, v)
    norm_u = np.linalg.norm(u)
    norm_v = np.linalg.norm(v)
    cos_theta = dot_product / (norm_u * norm_v)
    cos_theta = np.clip(cos_theta, -1.0, 1.0)
    theta_rad = np.arccos(cos_theta)
    return np.degrees(theta_rad)
def phep_chieu(u, v):
    tu_so = np.dot(u, v)
    mau_so = np.dot(v, v)
    p = (tu_so / mau_so) * v
    return p
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

kc = khoang_cach(u, v)
print("a) Khoảng cách giữa u và v:", kc)

goc = goc_giua(u, v)
print("b) Góc giữa u và v (độ):", goc)

p = phep_chieu(u, v)
print("c) Phép chiếu trực giao của u lên v:", p)


a) Khoảng cách giữa u và v: 5.196152422706632
b) Góc giữa u và v (độ): 12.933154491899135
c) Phép chiếu trực giao của u lên v: [1.66233766 2.07792208 2.49350649]
