In [1]:
import numpy as np
import math

# Khai báo vector và ma trận
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])

# a) Tính tổng A + B và tích số 2A + 3B
sum_AB = A + B
linear_combination = 2 * A + 3 * B

# b) Tính tích vô hướng A.B và góc giữa chúng
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_degrees = math.degrees(math.acos(cos_theta))

# c) Tính tích CC^T
CCT = np.dot(C, C.T)

# In kết quả
print("a) Tổng A + B:", sum_AB)
print("   Tích số 2A + 3B:", linear_combination)
print("\nb) Tích vô hướng A · B:", dot_product)
print("   Góc giữa hai vector (độ):", round(angle_degrees, 3))
print("\nc) Ma trận CC^T:\n", CCT)


a) Tổng A + B: [2 3 1 6]
   Tích số 2A + 3B: [ 3 11  2 14]

b) Tích vô hướng A · B: -5
   Góc giữa hai vector (độ): 99.594

c) Ma trận CC^T:
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]
