In [1]:
import numpy as np

# Khai báo ma trận
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])

N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])

# a) Tính tích M x N
product = np.dot(M, N)

# b) Tính định thức của M
det_M = np.linalg.det(M)

# c) Tính hạng của N
rank_N = np.linalg.matrix_rank(N)

# In kết quả
print("a) Ma trận M x N:\n", product)
print("\nb) Định thức của ma trận M:", round(det_M, 3))
print("\nc) Hạng của ma trận N:", rank_N)


a) Ma trận M x N:
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b) Định thức của ma trận M: 409.0

c) Hạng của ma trận N: 4
