In [1]:
import numpy as np

# Khai báo ma trận và vector
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])

b = np.array([6, 8, 3, 7])

# a) Tìm ma trận nghịch đảo của P
det_P = np.linalg.det(P)
print("a) Định thức của P:", round(det_P, 3))

if det_P != 0:
    P_inv = np.linalg.inv(P)
    print("Ma trận nghịch đảo của P:\n", P_inv)
else:
    print("Ma trận P không khả nghịch vì định thức bằng 0.")

# b) Giải hệ phương trình bằng nghịch đảo
if det_P != 0:
    x = np.dot(P_inv, b)
    print("\nb) Nghiệm của hệ phương trình là:\n", x)
else:
    x = None

# c) Kiểm tra lại nghiệm
if x is not None:
    check = np.dot(P, x)
    print("\nc) Kiểm tra lại P · x:\n", check)
    print("So sánh với vector hằng số b:", b)
    print("Có đúng không? ", np.allclose(check, b))


a) Định thức của P: 140.0
Ma trận nghịch đảo của P:
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]

b) Nghiệm của hệ phương trình là:
 [2.         1.71428571 0.42857143 0.85714286]

c) Kiểm tra lại P · x:
 [6. 8. 3. 7.]
So sánh với vector hằng số b: [6 8 3 7]
Có đúng không?  True
