In [1]:
import numpy as np

# Ma trận hệ số R và vector b
R = np.array([[4, -1, 2],
              [1, 3, -2],
              [0, 2, 5]])
b = np.array([12, 5, 9])

# a) Giải hệ phương trình Rx = b
x = np.linalg.solve(R, b)
print("a) Nghiệm x của hệ phương trình Rx = b là:\n", x)

# b) Kiểm tra khả nghịch của R
det_R = np.linalg.det(R)
print("\nb) Định thức của R:", det_R)

if det_R != 0:
    print("=> Ma trận R khả nghịch.")
    
    # Tính ma trận nghịch đảo
    R_inv = np.linalg.inv(R)
    print("Ma trận nghịch đảo R^-1 là:\n", R_inv)

    # Giải hệ bằng R^-1 * b
    x_via_inverse = R_inv @ b
    print("Nghiệm tìm được bằng R^-1 * b là:\n", x_via_inverse)

    # So sánh với nghiệm ban đầu
    diff = np.allclose(x, x_via_inverse)
    print("So sánh nghiệm: ", "Trùng khớp" if diff else "Khác nhau")
else:
    print("=> Ma trận R không khả nghịch.")

# c) Tính chuẩn Frobenius của ma trận R
fro_norm = np.linalg.norm(R, ord='fro')
print("\nc) Chuẩn Frobenius của ma trận R là:", fro_norm)


a) Nghiệm x của hệ phương trình Rx = b là:
 [2.78823529 1.52941176 1.18823529]

b) Định thức của R: 85.00000000000001
=> Ma trận R khả nghịch.
Ma trận nghịch đảo R^-1 là:
 [[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
Nghiệm tìm được bằng R^-1 * b là:
 [2.78823529 1.52941176 1.18823529]
So sánh nghiệm:  Trùng khớp

c) Chuẩn Frobenius của ma trận R là: 8.0
